# Generated by Django 3.1.4 on 2021-01-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittereb', '0002_auto_20210111_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='tw_tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('image_path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
