# Generated by Django 3.1.4 on 2021-01-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittereb', '0003_auto_20210113_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tw_tweet',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tw_tweet',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
