# Generated by Django 3.1.4 on 2021-01-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittereb', '0004_auto_20210114_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='rp_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('tw_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twittereb.tw_tweet')),
            ],
        ),
    ]
