# Generated by Django 3.1.4 on 2021-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittereb', '0007_auto_20210122_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tw_tweet',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
